### PR TITLE
LATAM support

### PR DESCRIPTION
**Pull request by izu-co**

### CODE REVIEW

**Comment by izu-co** [comment]
@alfablac @OryWareKyrie

I have a version that is working with my VPN while introducing the smallest amount of change (the Territory system is not implemented or example). Since this is working with my VPN tho I don't know if this is too little for people coming from LATAM, so I want you to check it out for me :).

PS: @OryWareKyrie for you I have included the builds so you can test it as well.
[funimation-downloader-nx-4.9.4-win64.zip](https://github.com/izu-co/funimation-downloader-nx/files/6949349/funimation-downloader-nx-4.9.4-win64.zip)
[funimation-downloader-nx-4.9.4-macos64.zip](https://github.com/izu-co/funimation-downloader-nx/files/6949355/funimation-downloader-nx-4.9.4-macos64.zip)

**Comment by OryWareKyrie** [comment]
@izu-co 

speak manin!!! I'm sorry for not replying yesterday, I saw the message but I didn't have time to test this version. I tested the coded version and it worked here for me. however I noticed that during the download it stops, it is necessary to stop the process and run again. I will do other tests during the day to better analyze this, it could be my internet:smile:

**Comment by izu-co** [comment]
Strange. I didn't encounter any stops? If this keeps happing, it would be nice if you can send me the logs.

**Comment by izu-co** [comment]
@OryWareKyrie Can you update me on whether the stops keep happening and if so steps with I may be able to reproduce them.

**Comment by izu-co** [comment]
Since this repository will merge with the main repository, I am going to assume that this PR is working and will merge it. 

If it doesn't work, make sure to create an issue at the main repo.

**Pull request merged**
